var krawczyk = [
  "Znałem cyganeczkę Zosię",
  "Kazali mi ją poślubić,",
  "Lecz me serce nie pozwala",
  "Mojej cyganeczki lubić, hej",
  "Lecz me serce nie pozwala",
  "Mojej cyganeczki lubić.",
  "Na podwórzu , na podwórzu",
  "Cztery kare konie stoją,",
  "Lecz ty śliczna cyganeczko",
  "Nigdy już nie będziesz moją, hej",
  "Lecz ty śliczna cyganeczko",
  "Nigdy już nie będziesz moją.",
  "A jak mi się znudzi wreszczie",
  "Kupię sobie konia w mieście,",
  "Kupię konia i aksamit",
  "I pojadę z cyganami, hej",
  "Kupię konia i aksamit",
  "I pojadę z cyganami.",
  "Jadę w Polskę z taborami",
  "Koniom grzywy wiatr rozwiewa,",
  "A ja jadę z cyganami",
  "I o cyganeczce śpiewam, hej",
  "A ja jadę z cyganami",
  "I o cyganeczce śpiewam.",


  "Chciałem być marynarzem",
  "chciałem mieć tatuaże",
  "podróżować, zwiedzać świat",
  "pięknie żyć, garściami życie brać",
  "chciałem być piosenkarzem",
  "chciałem mieć pełne sale",
  "podróżować, zwiedzać świat",
  "i wiele pięknych, pięknych kobiet znać",
  "przemierzyłem cały świat od Las Vegas po Krym",
  "zgrałem tysiąc talii kart, które lubią dym",
  "skasowałem kilka bryk, nie żałuję dziś",
  "nie żałuję dziś",
  "chciałem dać coś dobrego",
  "dałem tylko siebie",
  "los okrutnie ze mnie drwił",
  "gorzkich nauk nie oszczędził mi",
  "chciałem wnieść coś nowego",
  "chciałem mieć więcej wiary",
  "los okrutnie ze mnie drwił",
  "mojej wiary nie odebrał mi",

  "Chciałbym leżeć w trawie",
  "Chciałbym być szczęściarzem",
  "Chciałbym mieć milion marzeń",
  "I móc zmienić los",
  "Chciałbym więcej przeżyć",
  "Chciałbym w coś zawsze Wierzyc",
  "Chciałbym móc zatrzymać czas",
  "I żyć niejeden raz",

  "Niech spadnie na nas tysiąc gwiazd",
  "Oświetli moja drogę, znajdę znak",
  "I niech zawieje silny wiatr",
  "Przegoni ciemne chmury wokół nas",

  "Chciałbym być na plaży",
  "Chciałbym być szczęściarzem",
  "Chciałbym mieć milion marzeń",
  "I móc zmienić los",
  "Chciałbym więcej wiedzieć",
  "Zawsze mieć czas dla Ciebie",
  "Chciałbym znać nadziei smak",
  "I żyć niejeden raz",

  "Niech spadnie na nas tysiąc gwiazd",
  "Oświetli moja drogę, znajdę znak",
  "I niech zawieje silny wiatr",
  "Przegoni ciemne chmury wokół nas",

  "W roztańczeniu, w zapomnieniu, ile tchu,",
  "Zaplątana w tłum codziennych spraw,",
  "Nie słyszysz już, jak bije puls,",
  "Tak wciągnęła cię szalona gra.",

  "Gdy na uśmiech i nadzieję starczy sił -",
  "W kalendarzu jest tak wiele dat,",
  "A każda z nich wciąż nabija rytm",
  "Niespokojny tak jak ty.",

  "Dzień za dniem",
  "Przed znudzeniem uciekasz,",
  "Dzień za dniem",
  "Życie zmieniasz w sen.",
  "Dzień za dniem",
  "Wracasz tu z daleka,",
  "Bo ty wiesz, że nikt inny nie,",
  "Nie umie tak, nie potrafi tak",
  "Z przegranej w głos się śmiać.",

  "Choć mija czas,",
  "Lecz nie zmienia nas,",
  "Wciąż ty to ty, a ja to ja.",

  "Dzień za dniem",
  "Przed znudzeniem uciekasz,",
  "Dzień za dniem",
  "Życie zmieniasz w sen.",
  "Dzień za dniem",
  "Wracasz tu z daleka,",
  "Bo ty wiesz, że nikt inny nie,",
  "Nie umie tak powtarzać wciąż",
  "Szczęśliwy los. To jest właśnie to!",

  "Przypłynęłaś tu wraz z rzeką zadyszanych aut",
  "Potem sama w drzwiach przekręciłaś klucz",
  "Popatrz, włosy rozrzucone, cień na ziemię padł",
  "Z powitań moich tu przychodzisz",

  "A dziewczyny z mego miasta",
  "Co dzień rano biegną w życie",
  "Czasem w jakiś wiersz wtulają twarz",
  "Łowią wiatr w letni płaszcz",
  "A dziewczyny z mego miasta",
  "Pamiętniki piszą skrycie",
  "Niespokojnym sercem pragnąc, by",
  "Ktoś się chciał o nie bić",

  "Czy to pierwszy krok w obłoki czy na ziemię krok?",
  "Sierpień zerwał się z potrąconych strun",
  "Popatrz, tańczy ćma na szybie, auta goni wzrok",
  "Z pożegnań moich tu przychodzisz",

  "A dziewczyny z mego miasta",
  "Co dzień rano biegną w życie",
  "Czasem w jakiś wiersz wtulają twarz",
  "Łowią wiatr w letni płaszcz",
  "A dziewczyny z mego miasta",
  "Pamiętniki piszą skrycie",
  "Niespokojnym sercem pragnąc, by",
  "Ktoś się chciał o nie bić",

  "Jak cień, jak sen to wspomnienie,",
  "Powraca w podróży do tamtych lat.",
  "Pamiętam ten dzień powiedziałaś mi że,",
  "Dziś odkryłaś tę płytę i ten głos.",
  "Co dzień, co noc czy pamiętasz,",
  "To on Ciebie rzucił w ramiona me.",
  "Gdy głos jego brzmiał jak szum „Blue Hawai”,",
  "Tak ciepły, jak ciepło Twych ust.",

  "Gdy nam śpiewał Elvis Presley",
  "Świat miał trochę więcej barw",
  "Pod palmami „Blue Hawai”",
  "Kołysało „Good Luck Charm”",
  "„Love me tender” kochaj czule",
  "Na prywatce aż po świt",
  "„Kiss me Quick” pocałuj szybko",
  "Gdy nam Elvis śpiewa tak",

  "Jak cień, jak sen to wspomnienie,",
  "Choć tyle zabłysło na niebie gwiazd.",
  "To Ty dałeś nam piosenki co w świat,",
  "Wiodły nas przez trudny ten czas.",

  "Gdy nam śpiewał Elvis Presley",
  "Świat miał trochę więcej barw",
  "Pod palmami „Blue Hawai”",
  "Kołysało „Good Luck Charm”",
  "„Love me tender” kochaj czule",
  "Na prywatce całą noc",
  "„Kiss me Quick” pocałuj szybko",
  "Gdy nam Elvis śpiewa tak",

  "Zawsze uśmiechnięta",
  "Przykrych nie pamięta słów",
  "Z dnia na dzień wierniejsza",
  "Z dnia na dzień piękniejsza od snu",

  "Chcesz mieć miłą dziewczynę?",
  "To poszukaj Halinę",
  "Bardzo kocham to imię",
  "Bo Halinę mam ja",

  "W domu wysprzątane",
  "Dżinsy załatane w mig",
  "Na nic nie narzeka",
  "Na twój powrót czeka u drzwi",

  "Chcesz mieć dobrą dziewczynę?",
  "Wybierz sobie Halinę",
  "Bardzo kocham to imię",
  "Bo Halinę mam ja",

  "Więc jeśli",
  "Chcesz mieć klasa dziewczynę",
  "Wybierz sobie Halinę",
  "Bo bardzo kocham to imię",
  "Dziś Halinę mam ja",

  "Ooo... mam ja",

  "Chcesz mieć klasa dziewczynę?",
  "Zawsze wybierz Halinę",
  "Bardzo kocham to imię",
  "Bo Halinę mam ja",

  "Chcesz mieć klasa dziewczynę?",
  "Zawsze wybierz Halinę",
  "Bardzo lubię to imię",
  "Bo Halinę mam ja",

  "Zawsze uśmiechnięta",
  "Myśli odgaduje w lot",
  "Nawet nie pamiętam",
  "Za co w końcu kocham tak ją",

  "Koncert dnia jak przedwieczorny blues",
  "Radio gra, opada z słońca kurz",
  "Poczekaj, nie spiesz się",
  "Gazetę kupię, zapnę płaszcz",
  "Zdążymy na ostatni rejs",
  "W poduszkę wtulisz twarz",

  "Światła lamp opadną w rzeki nurt",
  "Wrócę sam, lotniska ścichnie szum",
  "Wypiję kawy haust",
  "Przeczytam twój ostatni list",
  "Przemyślę wszystko jeszcze raz",
  "Zerwany przejrzę film",

  "I pierwszy raz, płynąc pod prąd",
  "Znajdę lub nie stały swój ląd",
  "I wtedy sam, rwąc zdarzeń nić",
  "Spytam, jak żyć, jak żyć",

  "Sierpień już, mniej barwne szkiełka dni",
  "Z polnych bruzd horoskop złożę ci:",
  "Popłyniesz jachtem snów",
  "Daleko za granicę dnia",
  "Szczęśliwszej rzeki znajdziesz nurt",
  "I czas na serca ład",

  "No a ja w śródmiejski wejdę tłum",
  "Jedna łza nie piecze tak jak sól",
  "Sam przejrzę stertę zdjęć",
  "Przypomnę sobie miejsca, dni",
  "Z zadumą lekką spojrzę wstecz",
  "Otworzę szerzej drzwi",

  "Nie pierwszy raz, płynąc pod prąd",
  "Znajdę lub nie stały swój ląd",
  "I wreszcie sam, rwąc zdarzeń nić",
  "Spytam, jak żyć, jak żyć",

  "Nie pierwszy raz będzie mi żal",
  "Że to nie ty staniesz w tych drzwiach",
  "Że to nie ty podasz mi dłoń",
  "Gdy z góry nam skłoni się dzwon",

  "Nie pierwszy raz, płynąc pod prąd",
  "Znajdę lub nie stały swój ląd",
  "I wreszcie sam, rwąc zdarzeń nić",
  "Spytam, jak żyć, jak żyć",

  "Nie pierwszy raz będzie mi żal",
  "Że to nie ty staniesz w tych drzwiach",
  "Że to nie ty podasz mi dłoń",
  "Gdy z góry nam skłoni się dzwon",

  "Mój przyjacielu, byłeś mi naprawdę bliski,",
  "Mój przyjacielu, wiesz, że byłeś mi, jak brat",
  "Dałem ci wiarę, dałem ci spokój,",
  "Dałem gitarę, dałem samochód",
  "I dach nad głową, a do sypialni wszedłeś sam.",

  "Mój przyjacielu, przyprowadziłem cię z ulicy",
  "Nakarmiłem, odziałem cię, jak brat.",
  "Dałem ci wiarę, dałem ci spokój,",
  "Dałem gitarę, dałem samochód.",
  "Żony nie dałem, żonę wziąłeś sobie sam.",

  "Dał gitarę, dał samochód - żony nie dał, ju!",

  "Refren:",
  "Teraz pijesz wino, pijesz aż do dna,",
  "Późna już godzina, próżno czekasz dnia.",
  "Chciałbyś się rozpłynąć, uciec, gdzie się da.",
  "Proszę zostań na noc, przyjaźń swoje prawa ma.",

  "Teraz pijesz wino, pijesz aż do dna,",
  "Późna już godzina, próżno czekasz dnia.",
  "Chciałbyś się rozpłynąć, uciec, gdzie się da.",
  "Może spać spokojnie, kto przyjaźni prawa zna.",

  "Mój przyjacielu, jak wyrazić to, co czuję",
  "Jak wytłumaczyć, czym jest dla mnie przyjaźń Twa",
  "Dałem ci wiarę, dałem ci spokój,",
  "Dałem gitarę, dałem samochód.",
  "Żony nie dałem, żonę wziąłeś sobie sam.",

  "Mój przyjacielu, byłeś mi naprawdę bliski,",
  "Mój przyjacielu, wiesz, że byłeś mi, jak brat",
  "Dałem ci wiarę, dałem ci spokój,",
  "Dałem gitarę, dałem samochód.",
  "Żony nie dałem, żonę wziąłeś sobie sam.",

  "Dał gitarę, dał samochód - żony nie dał, ju!",

  "Refren:",
  "Teraz pijesz wino, pijesz aż do dna,",
  "Późna już godzina, próżno czekasz dnia.",
  "Chciałbyś się rozpłynąć, uciec, gdzie się da.",
  "Lepiej zostań na noc, przyjaźń swoje prawa ma.",

  "Teraz pijesz wino, pijesz aż do dna,",
  "Późna już godzina, próżno czekasz dnia.",
  "Chciałbyś się rozpłynąć, uciec, gdzie się da.",
  "Może spać spokojnie, kto przyjaźni prawa zna",

  "Dał gitarę, dał samochód - żony nie dał, ju!",

  "My Cyganie co pędzimy z wiatrem,",
  "my Cyganie znamy cały świat!",
  "My Cyganie wszystkim gramy,",
  "a śpiewamy sobie tak:",

  "Ore, ore sza ba da ba da amore.",
  "Hej! Amore sza ba da ba da.",
  "O muriaty, o szagriaty,",
  "hajda trojka na mienia! (bis)",

  "Kiedy tańczę, niebo tańczy ze mną.",
  "Kiedy gwiżdżę, gwiżdże polu wiatr",
  "Zamknę oczy, liście więdną,",
  "kiedy milknę, milczy świat.",

  "Gdy śpiewamy, słucha cała Ziemia.",
  "Gdy śpiewamy, śpiewa każdy ptak",
  "Niechaj każdy z nami śpiewa,",
  "niech rozbrzmiewa piosnka ta.",

  "Kiedy słucham,słucha cała ziemia",
  "i jak śpiewam, śpiewa każdy z nas",
  "gdy ucichnę wiatru nie ma",
  "Zamknę oczy nie ma gwiazd",

  "Będzie prościej, będzie jaśniej",
  "całą radość damy wam",
  "Będzie prościej, będzie jaśniej,",
  "gdy zaśpiewa każdy z was",

  "Można zamknąć serce przed miłością",
  "I uczynić najsilniejszą z twierdz.",
  "W taką noc ktoś jakby więzy rozciął,",
  "Miłość wchodzi w taką noc do serc.",

  "Nie kochać w taką noc to grzech,",
  "Gdy sercu serca brak.",
  "Bez tego pusty dźwięk ma śmiech",
  "I wino traci smak.",
  "Nie kochać w taką noc to grzech,",
  "Gdy tęsknią serca dwa.",
  "Gdy ktoś miłości wart jak ty,",
  "Ktoś o niej śni jak ja.",

  "Czy dzień, czy wiek cię znam,",
  "To przecież rzecz obojętna.",
  "Przyjemnie z sobą nam",
  "W tę dziwną, pijaną noc.",
  "Nie kochać w taką noc to grzech,",
  "Kochajmy, póki czas!",
  "Niech miłość wejdzie w krew i myśl,",
  "Niech porwie dziś i nas.",

  "Czy dzień, czy wiek cię znam,",
  "To przecież rzecz obojętna.",
  "Przyjemnie z sobą nam",
  "W tę dziwną, pijaną noc.",
  "Nie kochać w taką noc to grzech,",
  "Kochajmy, póki czas!",
  "Niech miłość wejdzie w krew i myśl,",
  "Niech porwie dziś i nas.",

  "Jeszcze sam się uczę siebie",
  "Żyję tak, jak umiem żyć",
  "Do utraty tchu",
  "Raz mi gorzej z tym, raz lepiej",
  "Rzucam się w zdarzeń rwący nurt",

  "Jak w ucieczce, jak w podróży",
  "Do zamkniętych pukam drzwi",
  "Byle serce nieść",
  "I choć nic się nie powtórzy",
  "Jeszcze raz myślą sięgam wstecz",

  "O! Jest gdzieś niebo jak len",
  "O, o, o! Noc za krótka na sen",
  "O! Dom, gdzie czeka znów ktoś",
  "I gdzie miejsca jest dość",
  "Dla spóźnionych gości",
  "O! Twój rysunek na szkle",
  "Tylko na nim już dziś nie ma mnie",

  "Idę dalej, żyję prędzej",
  "Pragnę, tracę to, co mam",
  "Czas doradcą złym",
  "Wieczorami piszę wiersze",
  "Chociaż ty już nie czytasz ich",

  "Biegną wiosny i jesienie",
  "Coraz bardziej dzieli nas",
  "Morze zwykłych spraw",
  "Mam już tylko to wspomnienie",
  "Choć i w nim mniej tych jasnych barw",

  "O! Jest gdzieś niebo jak len",
  "O, o, o! Noc za krótka na sen",
  "O! Dom, gdzie czeka znów ktoś",
  "I gdzie miejsca jest dość",
  "Dla spóźnionych gości",
  "O! Twój rysunek na szkle",
  "Tylko na nim już dziś nie ma mnie",

  "Ale kiedyś sam w pół drogi",
  "Stanę, cisnę nagle w kąt",
  "Cały ten mój świat",
  "Twarz ochłodzę kroplą wody",
  "Jakby mi znów ubyło lat",

  "I odnajdę tamten ogień",
  "I gościnny domu próg",
  "I przyjazną dłoń",
  "Lecz czy tamtą twą urodę",
  "Zwróci nam rzeki bystra toń?",

  "O! Jest gdzieś niebo jak len",
  "O, o, o! Noc za krótka na sen",
  "O! Dom, gdzie czeka znów ktoś",
  "I gdzie miejsca jest dość",
  "Dla spóźnionych gości",
  "O! Twój rysunek na szkle",
  "Tylko na nim już dziś nie ma mnie",
  "Nie ma mnie",

  "Laj, la la la la la laj",
  "La la la la la laj",
  "La la la la la la",
  "Laj, la la la la la laj",
  "Laj la la la la laj",
  "La la la la la la",
  "Laj, la la la la la laj",
  "La la la la la laj",
  "La la la la la la...",

  "Po polskiej równinie głos niesie,",
  "by odbić się echem od Tatr.",
  "Powtarza ludzkie pragnienie,",
  "byś często przebywał wśród nas.",

  "Ojcu Świętemu Śpiewajmy,",
  "w podzięce zanieśmy mu pieśń.",
  "Ojcu Świętemu oddajmy",
  "serdeczność płynącą od serc.",

  "Dziś Polska Cię wita z radością",
  "i niesie dla Ciebie ten chleb,",
  "co z ziarna zwanego miłością",
  "zrodziła, by witać Cię znów.",

  "Ojcu Świętemu Śpiewajmy,",
  "w podzięce zanieśmy mu pieśń.",
  "Ojcu Świętemu oddajmy",
  "serdeczność płynącą od serc.",

  "Pielgrzymie strudzony podróżą,",
  "co niesiesz nadzieję przez świat,",
  "w ojczyźnie znajdziesz wytchnienie,",
  "a my chcemy słuchać Twych rad.",

  "Jak w Bogu układać swe życie,",
  "wolnością nauczyć się żyć,",
  "wśród ludzi spełniać pragnienie,",
  "by dobro znalazło swój byt.",

  "Ojcu Świętemu Śpiewajmy,",
  "w podzięce zanieśmy mu pieśń.",
  "Ojcu Świętemu oddajmy",
  "serdeczność płynącą od serc.",

  "Ojcu Świętemu Śpiewajmy,",
  "w podzięce zanieśmy mu pieśń.",
  "Ojcu Świętemu oddajmy",
  "serdeczność płynącą od serc.",

  "Ojcu Świętemu Śpiewajmy,",
  "w podzięce zanieśmy mu pieśń.",
  "Ojcu Świętemu oddajmy",
  "serdeczność płynącą od serc.",

  "Zamknij świat na klucz, wróć do mnie",
  "Żal za siebie rzuć, wróć do mnie",
  "Bo ja wciąż pamiętam ciebie z tamtych lat",
  "Wygnaj z serca chłód, wróć do mnie",
  "Jak najkrótszą z dróg, wróć do mnie",
  "Bo ja wciąż pamiętam ciebie z tamtych lat (ciebie z tamtych lat)",

  "Niech się dzieje co chce",
  "(Niech się dzieje co chce)",
  "Nam nie może być źle",
  "Kupię nam obrączki dwie",
  "Bo po to by ze sobą być, żyjemy ja i ty",

  "Jak stracony czas, wróć do mnie",
  "Jak już kiedyś raz, wróć do mnie",
  "Bo ja wciąż pamiętam ciebie z tamtych lat (ciebie z tamtych lat)",

  "I tak jak po burzy wraca słońce, po nocy dzień a po ziemie lato",
  "Tak ty wróć do mnie",
  "Dzisiaj już wiem, że w całym moim życiu",
  "Najbardziej, najbardziej kochałem ciebie z tamtych lat",

  "W starym albumie u mego dziadka",
  "Jest takie zdjęcie, istny cud",
  "Płynacy w falach, wsród mewek stadka",
  "Statek na parę sprzed lat stu",

  "Tłum marynarzy pokład mu zdobi",
  "Słonce na górze pięknie lśni",
  "Dobry fotograf to zdjecie zrobił",
  "Wszystko jak żywe, aż się cni",

  "Parostatkiem w piękny rejs, statkiem na parę w piękny rejs",
  "Przy wtórze klątw bosmana, głośnych krzyków aż od rana",
  "Tak śpiewnie dusza łka",

  "Kąpielowy kostium włóż i na pokładzie ciało złóż",
  "Bo tutaj szum maszyny, bo tutaj głosem dziewczyny",
  "Tak cudnie sruba gra",

  "Marynarze, marynarki proszę bardzo ladys and gentelman",
  "Marynarze proszę nie wychylać się za burtę",

  "Dziadek bosmanem był na tym statku",
  "Wsród majtków wzbudzał wiecznie strach",
  "Krzyczał, aż drżały na brzegach kwiatki",
  "Cała załoga stała we łzach",

  "Lecz kiedy dziadek fajkę zapalił",
  "Tytoń mu zaczął płuca grzać",
  "Dziadek coś nucił, tytoń się palił",
  "Marzył, by wieki mogł tam trwać",

  "Płakałaś - pozostały ślady łez,",
  "Żal i lęk utkany gdzieś na końcach rzęs.",
  "Kochana, Twoje łzy osuszył wiatr.",
  "Smutku welon z twarzy spadł, zaśpiewał ptak.",
  "Nie oglądaj się wstecz,",
  "Przeszłość ginie we mgle,",
  "Gdy przed nami tyle chwil,",
  "Jedno wiesz na pewno, wiesz, warto żyć.",

  "Znów nastał ciepły dzień i przestał padać deszcz,",
  "Z domu dobiega gwar, beztroski dzieci śmiech.",
  "Gdy jesteś przy nas, kochanie, nasze życie pełne jest barw,",
  "Gdy jesteś przy nas znów, tak bardzo chce się żyć!",

  "Wierzyłaś, że świat nie jest całkiem zły,",
  "Że Ci nie zabraknie sił, aby tu żyć.",
  "Kochana, wspierał Cię wiosenny wiatr,",
  "Lasów szum i słońca blask, i zapach traw.",
  "Nie oglądaj się wstecz,",
  "Przeszłość nie liczy się,",
  "Gdy przed nami tyle chwil,",
  "Jedno wiesz na pewno, wiesz, warto żyć !",

  "Znów nastał ciepły dzień i przestał padać deszcz,",
  "(Znów nastał dzień)",
  "Z domu dobiega gwar, beztroski dzieci śmiech.",
  "Gdy jesteś przy nas, kochanie, nasze życie pełne jest barw,",
  "(Życie pełne jest barw)",
  "Gdy jesteś przy nas znów, tak bardzo chce się żyć!",

  "Znów nastał ciepły dzień (ciepły dzień)",
  "I przestał padać deszcz (ciepły dzień)",
  "Znów nastał ciepły dzień (ciepły dzień)",
  "I przestał padać deszcz",

  "Mieliśmy dla siebie tyle chwil ",
  "przed nami otwierał się świat ",
  "i anioł nadziei przy nas był ",
  "a los był z nami za pan brat ",

  "Ty przyszłaś jak pierwsza letnia noc ",
  "i wniosłaś pogodę w me dni ",
  "więc każdy odkryty szczęścia ląd ",
  "imieniem zwałem twym ",

  "To co dał nam świat niespodzianie zabrał los ",
  "dobre chwile skradł niosąc w zamian bagaż ",
  "zwykłych trosk ",
  "To co dał nam świat to odeszło z biegiem lat ",
  "cóż wart jest dziś niewczesny żal ",
  "że los wziął to co dał. ",

  "Nie znałem przy tobie srogich zim ",
  "barwami rozkwitał nam mrok ",
  "gdy owoc dojrzewał w sadzie twym ",
  "to giął gałęzie do mych rąk ",

  "Nie chciałaś od życia wiele brać ",
  "radości dzieliłaś na pół ",
  "a smutkom patrzyłaś sama w twarz ",
  "gdy czasem przyszły tu. ",

  "Gdy sięgasz po kieliszek wina",
  "By uciec od codziennych trosk",
  "Radością wspiera cię dziewczyna",
  "Uśmiecha się znów los",
  "Nie miałeś w życiu wiele szczęścia",
  "Nie jeden spadł na ciebie cios",
  "Były powroty i odejścia",
  "Lecz zawsze był ten ktoś",

  "Życie jest za krótkie, żeby pić marne wino",
  "Życie jest za krótkie, by miłości dać zginąć",
  "Życie jest za krótkie, żeby się nie spieszyć",
  "Życie jest za krótkie, by się nim nie cieszyć",

  "Gdy taniec życia cię porywa ",
  "Nie idziesz wcale w zwykły tan ",
  "Wypijasz znów kieliszek wina ",
  "I coś ci w duszy gra",

  "Życie jest za krótkie, żeby pić marne wino",
  "Życie jest za krótkie, by miłości dać zginąć",
  "Życie jest za krótkie, żeby się nie spieszyć",
  "Życie jest za krótkie, by się nim nie cieszyć",

  "Życie jest za krótkie, żeby pić marne wino",
  "Życie jest za krótkie, by miłości dać zginąć",
  "Życie jest za krótkie, żeby się nie spieszyć",
  "Życie jest za krótkie, by się nim nie cieszyć"
]
